name: KBOT-CICD
on: 
  push:
    branches: develop
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run test
        run: make test

      - name: GitHub Docker Repo login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_TOKEN }}
      
      - name: Build & Push
        env:
          APP: "kbot"
          REGISTRY: ${{ secrets.REPO_REGISTRY }}
        run: make image push
  
  cd:
    name: CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        run: echo "VERSION=$(shell git describe --tags --abbrev=0)-$(shell git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Edit variables
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
      
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.io
          git commit -am "update version $VERSION"
          git push